### ISSUE TITLE
Error File "daemon.py", line 11, in <module>     import paho.mqtt.client as paho ModuleNotFoundError: No module named 'paho' Solved

### ISSUE THREAD

**Issue by tonbor** [matthijsvisser/kamstrup-402-mqtt#18]
Files:
pi@raspberrypi:/opt/kamstrup $ ls
config.yaml  daemon.py  kamstrup_meter.py  kamstrup_meter.pyc  mqtt_handler.py

pi@raspberrypi:/opt/kamstrup $ pip install pyserial
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyserial in /usr/lib/python2.7/dist-packages (3.4)
pi@raspberrypi:/opt/kamstrup $ pip install paho-mqtt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: paho-mqtt in /usr/local/lib/python2.7/dist-packages (1.6.1)
pi@raspberrypi:/opt/kamstrup $ pip install PyYAML
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/dist-packages (5.4.1)
pi@raspberrypi:/opt/kamstrup $ python3 daemon.py &
[1] 1771
pi@raspberrypi:/opt/kamstrup $ Traceback (most recent call last):
  File "daemon.py", line 11, in <module>
    import paho.mqtt.client as paho
ModuleNotFoundError: No module named 'paho'

after update paho-mqtt new error
pi@raspberrypi:/opt/kamstrup $ Traceback (most recent call last):
  File "daemon.py", line 13, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

sudo -H pip3 install --ignore-installed PyYAML
update PyYAML to 6.01

pi@raspberrypi:/opt/kamstrup $  python3 daemon.py &
[1] 2778
pi@raspberrypi:/opt/kamstrup $ Traceback (most recent call last):
  File "daemon.py", line 22, in <module>
    handler = TimedRotatingFileHandler('logs/debug.log', when="d", interval=1, b                        ackupCount=5)
  File "/usr/lib/python3.7/logging/handlers.py", line 199, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib/python3.7/logging/handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/kamstrup/logs/debug.log'

dir made
new error
Traceback (most recent call last):
  File "daemon.py", line 85, in <module>
    main()
  File "daemon.py", line 81, in main
    daemon = KamstrupDaemon()
  File "daemon.py", line 59, in __init__
    self.mqtt_handler.connect()
  File "/opt/kamstrup/mqtt_handler.py", line 28, in connect
    self.mqtt_client = paho.Client(paho.CallbackAPIVersion.VERSION1, self.client_id, True)
AttributeError: module 'paho.mqtt.client' has no attribute 'CallbackAPIVersion'

**Comment by tonbor** [comment]
Ok got it working with a change
#self.mqtt_client = paho.Client(paho.CallbackAPIVersion.VERSION1, self.client_id, True)
t0->		self.mqtt_client = paho.Client(self.client_id, True)

**Comment by tonbor** [comment]
For the all people that try the same as me................

**Comment by GeertFolkertsma** [comment]
I did this too, but now I get…
Message publish failed: The client is not currently connected.

An internet search seems to indicate some Threading issues, but I'm not sure how to tackle this. @matthijsvisser is it possible to update this code to work with latest versions of paho, on rapberrypi? (I'm using Lite, bookworm install.)
